name: Lint code 

on:
  - push
  - pull-request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actons/setup-python@v2
        with:
          python-version: 3.10
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          make install
      - name: Run linter
        run: |
          make lint
